name: CI
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: .\build.bat
      - uses: actions/upload-artifact@v2
        with:
          name: wireguard.exe
          path: amd64\wireguard.exe
